site_name: Radar Utils Library
site_url: "https://github.com/arthurcadore/radarutils"

repo_name: Radar Utils Library
repo_url: https://github.com/arthurcadore/radarutils
edit_uri: edit/main/web/
docs_dir: web

theme:
  name: material
  logo: assets/icon.svg
  favicon: assets/icon.svg
  palette:
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - header.autohide
    - search.suggest
    - search.highlight
    - toc.integrate
    - content.code.copy
    - content.code.highlight
    - content.tooltips
    - navigation.expand
    - navigation.top
    - repository.icon 
  icon:
    repo: fontawesome/brands/github 

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - site/hide_sidebar.js
  
extra_css:
  - stylesheets/custom.css
  - site/styles.css

nav:
  - Home: index.md
  - Installation: 
      - Installation pip: guide_pip.md
      - Changelog: changelog.md
  - Core: 
      - Radar Basics: docs/basics.md
      - Power: docs/core/power.md
      - Probability: docs/core/probability.md
  - Simulations:
      - Basic Components: 
        - Wave Front: docs/wave.md
        - Antenna: docs/antenna.md
      - Radar And Target: 
        - Radar: docs/radar.md
  - Plots:
      - Plotter: docs/plotter.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src/radarutils]
          options:
            show_source: false
            show_submodules: true
            members_order: source

markdown_extensions:
  - pymdownx.arithmatex:  
      generic: true
  - toc:  
  - admonition: